const ADD_TO_CART = "ADD_TO_CART";
const INCREASE_QTY = "INCREASE_QTY"
const DECREASE_QTY = "DECREASE_QTY"
const REMOVE_FROM_CART = "REMOVE_FROM_CART "



export {ADD_TO_CART,REMOVE_FROM_CART,DECREASE_QTY,INCREASE_QTY }